### ISSUE TITLE
Normalize height of the select element

### ISSUE THREAD

**Issue by MattMcAdams** [MattMcAdams/CSS-Boilerplate#18]
Select element does not match height of other inputs when placed side by side. This seems to be because it is ignoring the line-height rule. After some investigation, this seems to fix the issue.

```css
/* Standardize select box sizing */
select {
  -webkit-appearance: menulist-button;
}
```

I'll need to test to make sure this doesn't affect the functionality or accessibility of the select element on mobile
